# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mobile Threat Catalogue
email: akeller@mitre.org
description: >
    <p> In order to fully address the inherent threats of mobile devices, a wider view of the mobile ecosystem is necessary.
        This repository contains the Mobile Threat Catalogue, which describes, identifies, and structures the threats posed to mobile information systems.
        The National Cybersecurity Center of Excellence (NCCoE) seeks comment on current mobile threats addressed in the Catalogue as well as ideas for additional threats to add.
        Visit the <a href="/mobile-threat-catalogue/contributing.html">contributing page</a> for more information on how to provide feedback.
    </p>
    <p>
        Readers of the catalogue may notice there are gaps proposed threats that are not tied to an origin source or do not have countermeasures, and threats that are missing.
        The NCCoE requests mobile security industry experts and researchers to help shape the catalogue by submitting edits and additions.
        Feedback can be submitted through this GitHub site. Visit the <a href="/mobile-threat-catalogue/contributing.html">contributing page</a> for directions.
    </p>
    <p>An associated report provide context and describing this repository is available here:
        <a href="https://nccoe.nist.gov/sites/default/files/library/mtc-nistir-8144-draft.pdf">NISTIR 8144: Assessing Threats to Mobile Devices & Infrastructure.</a>
    </p>
    <p>The comment period closes on Friday, October 7, 2016.</p>


baseurl: "/mobile-threat-catalogue" # the subpath of your site, e.g. /blog
url: "http://mrdrewkeller.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mrdrewkeller

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

collections:
    application-threats:
        output: true
    authentication-threats:
        output: true
    stack-threats:
        output: true
    cellular-threats:
        output: true
    ecosystem-threats:
        output: true
    emm-threats:
        output: true
    gps-threats:
        output: true
    lan-pan-threats:
        output: true
    payment-threats:
        output: true
    physical-threats:
        output: true
    supply-chain-threats:
        output: true
