# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mobile Threat Catalogue
email: akeller@mitre.org
description: > # Mobile devices pose a unique set of threats to the enterprise, but typical enterprise protections fail to address the larger picture.
    In order to fully address the threats mobile devices bring, a wider view of the mobile ecosystem is necessary.
    This repository contains the Mobile Threat Catalogue, which describes, identifies, and structures the threats posed to mobile information systems.<br />


    <br />An associated report describing this repository is available at NIST's Computer Security Resource Center at <a href="http://csrc.nist.gov">csrc.nist.gov</a><br />


    <br />The NCCoE is interested in receiving comments on the Mobile Threat Catalogue, ideas for future mobile security projects, and mobile security architectures
    operating and/or managing enterprise mobile deployments. The NCCoE is also interested in feedback from mobile technology vendors who may wish to work in
    collaboration to solve mobile security challenges. Visit the <a href="/mobile-threat-catalogue/contributing.html">contributing page</a> for more information on how to provide feedback.
baseurl: "/mobile-threat-catalogue" # the subpath of your site, e.g. /blog
url: "http://mrdrewkeller.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mrdrewkeller

# Build settings
markdown: kramdown
sass:
    sass_dir: _sass

collections:
    application-threats:
        output: true
    authentication-threats:
        output: true
    stack-threats:
        output: true
    cellular-threats:
        output: true
    ecosystem-threats:
        output: true
    emm-threats:
        output: true
    gps-threats:
        output: true
    lan-pan-threats:
        output: true
    payment-threats:
        output: true
    physical-threats:
        output: true
    supply-chain-threats:
        output: true
